import type { RobotTaskSequenceType } from "../../domain/robot-tasks";

/** Discriminator values supported by the internal IFC-like record graph. */
export type IfcRobotTaskRecordEntity =
  | "IfcTask"
  | "IfcTaskTime"
  | "IfcRelNests"
  | "IfcRelSequence"
  | "IfcRelAssignsToProcess"
  | "IfcRelAssignsToProduct"
  | "IfcRelDefinesByProperties"
  | "IfcPropertySet"
  | "IfcPropertySingleValue"
  | "IfcPropertyListValue";

/** Lightweight typed pointer between two generated IFC-like records. */
export interface IfcRecordReference<
  Entity extends IfcRobotTaskRecordEntity = IfcRobotTaskRecordEntity,
> {
  /** Entity type expected at the referenced record ID. */
  entity: Entity;

  /** Stable identifier of another record in the same mapping result. */
  id: string;
}

/**
 * Reference to an existing IFC model object that is not generated by this mapper.
 *
 * A later serializer or backend resolver can locate the original entity through
 * GlobalId, or through the model-scoped express ID fallback when necessary.
 */
export interface IfcExternalObjectReference {
  /** Marks this value as an external model entity rather than a generated record. */
  kind: "IfcObjectReference";

  /** Preferred durable IFC identity. */
  globalId?: string;

  /** Runtime model that scopes a model-local express ID. */
  modelId?: string;

  /** Optional model-local IFC express ID. */
  expressId?: number;

  /** Optional IFC entity class copied from the domain reference. */
  ifcClass?: string;

  /** Optional human-readable source object name. */
  name?: string;
}

/** Shared fields carried by every generated IFC-like record. */
interface IfcRecordBase<Entity extends IfcRobotTaskRecordEntity> {
  /** IFC entity represented by this internal record. */
  entity: Entity;

  /** Stable graph-local identifier used by relation references. */
  id: string;
}

/** Internal representation of a mission parent task or executable child task. */
export interface IfcTaskRecord extends IfcRecordBase<"IfcTask"> {
  /** Domain mission or task ID from which this record was generated. */
  sourceId: string;

  /** Distinguishes the summary mission task from executable child tasks. */
  role: "MISSION" | "EXECUTABLE_TASK";

  /** Human-readable task name. */
  name: string;

  /** Optional longer task or mission description. */
  description?: string;

  /** Direct IfcTask.TaskTime-style reference, never a property relation. */
  taskTime?: IfcRecordReference<"IfcTaskTime">;
}

/** Internal representation of direct scheduling data owned by one IfcTask. */
export interface IfcTaskTimeRecord extends IfcRecordBase<"IfcTaskTime"> {
  /** Domain task ID that owns this timing record. */
  sourceTaskId: string;

  /** Planned start value copied from RobotTaskTime. */
  scheduleStart?: string;

  /** Planned finish value copied from RobotTaskTime. */
  scheduleFinish?: string;

  /** Planned duration value copied from RobotTaskTime. */
  scheduleDuration?: string;

  /** Recorded execution start value. */
  actualStart?: string;

  /** Recorded execution finish value. */
  actualFinish?: string;

  /** Estimated remaining duration. */
  remainingTime?: string;

  /** Completion ratio in the inclusive range from zero to one. */
  completion?: number;
}

/** Internal representation of mission-to-child hierarchy through IfcRelNests. */
export interface IfcRelNestsRecord extends IfcRecordBase<"IfcRelNests"> {
  /** Parent mission IfcTask. */
  relatingObject: IfcRecordReference<"IfcTask">;

  /** Executable child IfcTasks in mission hierarchy order. */
  relatedObjects: IfcRecordReference<"IfcTask">[];
}

/** Internal representation of one directed temporal task dependency. */
export interface IfcRelSequenceRecord extends IfcRecordBase<"IfcRelSequence"> {
  /** Predecessor process. */
  relatingProcess: IfcRecordReference<"IfcTask">;

  /** Successor process. */
  relatedProcess: IfcRecordReference<"IfcTask">;

  /** Temporal semantics copied from RobotTaskSequence. */
  sequenceType: RobotTaskSequenceType;
}

/** Supported semantic names for object-to-process assignments. */
export type IfcProcessAssignmentName =
  | "OPERATES_ON"
  | "AFFECTS"
  | "PASSES_THROUGH"
  | "NAVIGATES_TO"
  | "MOVE_FROM";

/** Internal representation of task interaction with one or more IFC objects. */
export interface IfcRelAssignsToProcessRecord
  extends IfcRecordBase<"IfcRelAssignsToProcess"> {
  /** Semantic role of the related existing model objects. */
  name: IfcProcessAssignmentName;

  /** Executable IfcTask that performs the operation. */
  relatingProcess: IfcRecordReference<"IfcTask">;

  /** Existing IFC objects targeted, affected, traversed, or used as origin. */
  relatedObjects: IfcExternalObjectReference[];
}

/** Internal representation of a MOVE task destination through IfcRelAssignsToProduct. */
export interface IfcRelAssignsToProductRecord
  extends IfcRecordBase<"IfcRelAssignsToProduct"> {
  /** Semantic movement role; currently only the required MOVE_TO relation. */
  name: "MOVE_TO";

  /** MOVE IfcTask associated with the destination product or spatial reference. */
  relatedObjects: IfcRecordReference<"IfcTask">[];

  /** Existing IFC object used as the movement destination. */
  relatingProduct: IfcExternalObjectReference;
}

/** Internal representation of a task-to-property-set relationship. */
export interface IfcRelDefinesByPropertiesRecord
  extends IfcRecordBase<"IfcRelDefinesByProperties"> {
  /** Generated IfcTasks that own the concrete property values. */
  relatedObjects: IfcRecordReference<"IfcTask">[];

  /** Task-level custom property set. */
  relatingPropertyDefinition: IfcRecordReference<"IfcPropertySet">;
}

/** Internal representation of a custom task property set. */
export interface IfcPropertySetRecord extends IfcRecordBase<"IfcPropertySet"> {
  /** Custom property-set name without the reserved Pset_ prefix. */
  name: "RobotAction" | "RobotMission";

  /** Property records contained in this set. */
  hasProperties: Array<
    IfcRecordReference<"IfcPropertySingleValue" | "IfcPropertyListValue">
  >;
}

/** Scalar values supported by the internal property representation. */
export type IfcPropertyScalar = string | number | boolean;

/** Internal representation of one scalar action property. */
export interface IfcPropertySingleValueRecord
  extends IfcRecordBase<"IfcPropertySingleValue"> {
  /** RobotAction property name. */
  name: string;

  /** Concrete scalar value owned by the task property set. */
  nominalValue: IfcPropertyScalar;
}

/** Internal representation of one list-valued action property. */
export interface IfcPropertyListValueRecord
  extends IfcRecordBase<"IfcPropertyListValue"> {
  /** RobotAction property name. */
  name: string;

  /** Ordered concrete values owned by the task property set. */
  listValues: IfcPropertyScalar[];
}

/** Union of every record generated for a mapped RobotMission. */
export type IfcRobotTaskRecord =
  | IfcTaskRecord
  | IfcTaskTimeRecord
  | IfcRelNestsRecord
  | IfcRelSequenceRecord
  | IfcRelAssignsToProcessRecord
  | IfcRelAssignsToProductRecord
  | IfcRelDefinesByPropertiesRecord
  | IfcPropertySetRecord
  | IfcPropertySingleValueRecord
  | IfcPropertyListValueRecord;

/** Complete internal IFC-like graph generated from one RobotMission aggregate. */
export interface IfcRobotMissionRecordGraph {
  /** Domain mission ID represented by this graph. */
  missionId: string;

  /** Reference to the generated parent mission IfcTask. */
  rootTask: IfcRecordReference<"IfcTask">;

  /** Flat deterministic record collection suitable for later resolution. */
  records: IfcRobotTaskRecord[];
}
